version: '3'

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: chatapp
      POSTGRES_PASSWORD: chatapp123
      POSTGRES_DB: chatapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    networks:
      - chat_network

  envoy:
    image: envoyproxy/envoy:v1.28-latest
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "8080:8080"
      - "9901:9901"
    networks:
      - chat_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - chat_network
    depends_on:
      - backend
      - envoy

volumes:
  postgres_data:

networks:
  chat_network:
    driver: bridge 