/**
 * @fileoverview gRPC-Web generated client stub for chat
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.3
// source: proto/chat.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as proto_chat_pb from '../proto/chat_pb'; // proto import: "proto/chat.proto"


export class ChatServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorRegister = new grpcWeb.MethodDescriptor(
    '/chat.ChatService/Register',
    grpcWeb.MethodType.UNARY,
    proto_chat_pb.RegisterRequest,
    proto_chat_pb.AuthResponse,
    (request: proto_chat_pb.RegisterRequest) => {
      return request.serializeBinary();
    },
    proto_chat_pb.AuthResponse.deserializeBinary
  );

  register(
    request: proto_chat_pb.RegisterRequest,
    metadata?: grpcWeb.Metadata | null): Promise<proto_chat_pb.AuthResponse>;

  register(
    request: proto_chat_pb.RegisterRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_chat_pb.AuthResponse) => void): grpcWeb.ClientReadableStream<proto_chat_pb.AuthResponse>;

  register(
    request: proto_chat_pb.RegisterRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_chat_pb.AuthResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/chat.ChatService/Register',
        request,
        metadata || {},
        this.methodDescriptorRegister,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/chat.ChatService/Register',
    request,
    metadata || {},
    this.methodDescriptorRegister);
  }

  methodDescriptorLogin = new grpcWeb.MethodDescriptor(
    '/chat.ChatService/Login',
    grpcWeb.MethodType.UNARY,
    proto_chat_pb.LoginRequest,
    proto_chat_pb.AuthResponse,
    (request: proto_chat_pb.LoginRequest) => {
      return request.serializeBinary();
    },
    proto_chat_pb.AuthResponse.deserializeBinary
  );

  login(
    request: proto_chat_pb.LoginRequest,
    metadata?: grpcWeb.Metadata | null): Promise<proto_chat_pb.AuthResponse>;

  login(
    request: proto_chat_pb.LoginRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_chat_pb.AuthResponse) => void): grpcWeb.ClientReadableStream<proto_chat_pb.AuthResponse>;

  login(
    request: proto_chat_pb.LoginRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_chat_pb.AuthResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/chat.ChatService/Login',
        request,
        metadata || {},
        this.methodDescriptorLogin,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/chat.ChatService/Login',
    request,
    metadata || {},
    this.methodDescriptorLogin);
  }

  methodDescriptorSendMessage = new grpcWeb.MethodDescriptor(
    '/chat.ChatService/SendMessage',
    grpcWeb.MethodType.UNARY,
    proto_chat_pb.Message,
    proto_chat_pb.MessageResponse,
    (request: proto_chat_pb.Message) => {
      return request.serializeBinary();
    },
    proto_chat_pb.MessageResponse.deserializeBinary
  );

  sendMessage(
    request: proto_chat_pb.Message,
    metadata?: grpcWeb.Metadata | null): Promise<proto_chat_pb.MessageResponse>;

  sendMessage(
    request: proto_chat_pb.Message,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_chat_pb.MessageResponse) => void): grpcWeb.ClientReadableStream<proto_chat_pb.MessageResponse>;

  sendMessage(
    request: proto_chat_pb.Message,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_chat_pb.MessageResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/chat.ChatService/SendMessage',
        request,
        metadata || {},
        this.methodDescriptorSendMessage,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/chat.ChatService/SendMessage',
    request,
    metadata || {},
    this.methodDescriptorSendMessage);
  }

  methodDescriptorJoinChat = new grpcWeb.MethodDescriptor(
    '/chat.ChatService/JoinChat',
    grpcWeb.MethodType.SERVER_STREAMING,
    proto_chat_pb.JoinRequest,
    proto_chat_pb.ChatUpdate,
    (request: proto_chat_pb.JoinRequest) => {
      return request.serializeBinary();
    },
    proto_chat_pb.ChatUpdate.deserializeBinary
  );

  joinChat(
    request: proto_chat_pb.JoinRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<proto_chat_pb.ChatUpdate> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/chat.ChatService/JoinChat',
      request,
      metadata || {},
      this.methodDescriptorJoinChat);
  }

}

